
/**************** USER_AUTH ACTIONS **************************/
export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const USER_INFO = 'USER_INFO';
export const CR_OPENED = 'CR_OPENED';
export const USER_INFO_RECEIVED = 'USER INFO RECEIVED';
export const HYDRATE_USER_INFO = 'HYDRATE_USER_INFO';
export const USER_INFO_REQUESTING = 'USER INFO REQUESTING';
export const USER_INFO_FAILED = 'USER INFO FAILED';


export const STORE_REQUESTING = 'STORE REQUESTING';
export const STORE_FAILED = 'STORE FAILED';
export const STORE_FETCHED = 'STORE FETCHED';
export const STORE_SELECTED = 'STORE SELECTED';

export const STORE_PREF_REQUESTING = 'STORE PREF REQUESTING';
export const STORE_PREF_FAILED = 'STORE PREF FAILED';
export const STORE_PREF_FETCHED = 'STORE PREF FETCHED';
export const PAYMENT_OPTIONS = 'PAYMENT_OPTIONS';



export const CASH_REGISTERS_REQUESTING = 'CASH REGISTERS REQUESTING';
export const CASH_REGISTERS_FAILED = 'CASH REGISTERS FAILED';
export const CASH_REGISTERS_FETCHED = 'CASH REGISTERS FETCHED';
export const CASH_REGISTERS_SELECTED = 'CASH REGISTERS SELECTED';
export const CR_INVOICE_SERIES_INCREMENT = 'CR_INVOICE_SERIES_INCREMENT';
export const SYNC_COMPLETED = 'SYNC COMPLETED';
/************/

export const DUMMY = 'DUMMY';

/**************** BROWSE ACTIONS **************************/

export const BROWSE_CATEGORY_REQUESTING = 'BROWSE CATEGORY REQUESTING';
export const BROWSE_CATEGORY_FAILED = 'BROWSE CATEGORY FAILED';
export const BROWSE_CATEGORY_FETCHED = 'BROWSE CATEGORY FETCHED';
export const BROWSE_SUB_CATEGORY_FETCHED = 'BROWSE SUB CATEGORY FETCHED';
export const BROWSE_ITEMS_FETCHED = 'BROWSE ITEMS FETCHED';

/**************** ITEM ACTIONS **************************/

export const ADD_ITEM = 'ADD_ITEM';
export const ADD_ITEM_GUID = 'ADD_ITEM_GUID';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const UPDATE_USER_LIST = 'UPDATE_USER_LIST';
export const UPDATE_EMPLOYEE_LIST = 'UPDATE_EMPLOYEE_LIST';

export const REMOVE_CUSTOMER = 'ADD_CUSTOMER';
export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const REMOVE_EMPLOYEE = 'REMOVE_EMPLOYEE';
export const TAG_INVOICE_EMPLOYEE = 'TAG_INVOICE_EMPLOYEE';
export const TAG_INVOICE_CUSTOMER = 'TAG_INVOICE_CUSTOMER';
export const TAG_ITEM_EMPLOYEE = 'TAG_ITEM_EMPLOYEE';

export const ITEM_QUANTITY_INCREMENT = 'ITEM_QUANTITY_INCREMENT';
export const ITEM_QUANTITY_DECREMENT = 'ITEM_QUANTITY_DECREMENT';
export const ITEM_QUANTITY_FIXED = 'ITEM_QUANTITY_FIXED';
export const UPDATE_ITEM_PRICE = 'UPDATE_ITEM_PRICE';
export const UPDATE_ITEM_DISCOUNT = 'UPDATE_ITEM_DISCOUNT';
export const UPDATE_ALL_ITEMS_DISCOUNT = 'UPDATE_ALL_ITEMS_DISCOUNT';
export const SELECT_ITEM = 'SELECT_ITEM';
export const TOGGLE_INVOICE_LIST = 'TOGGLE_INVOICE_LIST';
export const TOGGLE_INVOICE_MENU = 'TOGGLE_INVOICE_MENU';
export const SHOW_INVOICE_LIST = 'SHOW_INVOICE_LIST';
export const SET_INITIAL_INVOICES = 'SET_INITIAL_INVOICES';
export const ADD_NEW_INVOICE = 'ADD_NEW_INVOICE';
export const RESET_INVOICE = 'RESET_INVOICE';
export const SHOW_DRAFT_INVOICES = 'GET_DRAFT_INVOICES';
export const REPLACE_CURRENT_INVOICE = 'REPLACE_CURRENT_INVOICE';

export const PROCESS_TO_PAY = 'PROCESS_TO_PAY';
export const UPDATE_INVOICE_REVISION = 'UPDATE_INVOICE_REVISION';

export const ALL_INVOICES_REQUESTING = 'ALL INVOICES REQUESTING';
export const ALL_INVOICES_FAILED = 'ALL INVOICES FAILED';
export const ALL_INVOICES_FETCHED = 'ALL INVOICES FETCHED';

export const MENU_OPTIONS_SELECTED = 'MENU OPTIONS SELECTED';

/******************* DIALOG ACTIONS ****************************************/

export const SHOW_DIALOG = 'SHOW_DIALOG';
export const DISMISS_DIALOG = 'DISMISS_DIALOG';
export const EDIT_CUSTOMER = 'EDIT_CUSTOMER';
export const UPDATE_CATEGORY_LIST = 'UPDATE_CATEGORY_LIST';
export const UPDATE_SUB_CATEGORY_LIST = 'UPDATE_SUB_CATEGORY_LIST';
export const ADD_TAX_DATA = 'ADD_TAX_DATA';

/**************** NUM_PAD ACTIONS **************************/

export const NUM_KEY_PRESS = 'NUM_KEY_PRESS';
export const DISPLAY_TEXT = 'DISPLAY_TEXT';
export const ACTION_KEY_PRESS = 'ACTION_KEY_PRESS';
export const RESET_NUM_PAD = 'RESET_NUM_PAD';
export const UPDATE_LAYOUT = 'UPDATE_LAYOUT';
export const DISABLE_NUMPAD = 'DISABLE_NUMPAD';

/************/

/**************** PAYMENTS ACTIONS **************************/

export const PAY_MODE_PRESS = 'PAY_MODE_PRESS';
export const PAY_MODE_ADDED = 'PAY_MODE_ADDED';
export const RESET_PAYMENTS = 'RESET_PAYMENTS';
export const INITIALIZE_PAYMENTS = 'INITIALIZE_PAYMENTS';
export const REMOVE_PAY_MODE = 'REMOVE_PAY_MODE';
export const ADD_PAYMODE_TXN = 'ADD_PAYMODE_TXN';
export const SHOW_PRINT_PREVIEW = 'SHOW_PRINT_PREVIEW';
export const SHOW_ZOPPER_PAY = 'SHOW_ZOPPER_PAY';

/************/

/**************** DB ACTIONS **************************/

export const SYNC = 'SYNC';

/************/


/**************** DASHBOARD ACTIONS *******************/

export const DASHBOARD_ACTION = 'DASHBOARD_ACTION';
export const DASHBOARD_REMOVE_ITEM = 'DASHBOARD_REMOVE_ITEM';
export const DASHBOARD_ADD_ITEM = 'DASHBOARD_ADD_ITEM';
export const SHOW_SELECT_ITEM_DIALOG = 'SHOW_SELECT_ITEM_DIALOG';
export const SHOW_UNKNOWN_ITEM_ID = 'SHOW_UNKNOWN_ITEM_ID';
export const SELECT_TAB = 'SELECT_TAB';
export const DISCOUNT_TEXT = 'DISCOUNT_TEXT';
export const SEARCH_RESULT = 'SEARCH_RESULT';
export const CLEAR_SEARCH_RESULT = 'CLEAR_SEARCH_RESULT';


/************/
